version: '3.4'

services:
  library.service:
    image: ${DOCKER_REGISTRY-}libraryservice
    container_name: library.service
    build:
      context: .
      dockerfile: Backend/Domain/Library/Library.Service/Dockerfile
    restart: on-failure
    ports:
      - 8082:8080
      - 8083:8081
    networks:
      - backend
  full-stack-ng:
    image: ${DOCKER_REGISTRY-}client.angular
    container_name: client.angular
    environment:
      - KEYCLOAK_URL=http://localhost:8081
      - KEYCLOAK_REALM=fullstack
      - KEYCLOAK_CLIENT_ID=frontend
      - AUTHORS_URL=http://localhost:8082/api/authors
    build:
      context: FrontEnd/Angular/full-stack-ng
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8086:80
    networks:
      - backend
  security.service:
    image: ${DOCKER_REGISTRY-}securityservice
    container_name: security.service
    build:
      context: .
      dockerfile: Backend/Infrastructure/Security/Security.Service/Dockerfile
    ports:
      - 8084:80
      - 8085:443
    networks:
      - backend
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234
    volumes:
      - ./Backend/Infrastructure/Database/mssql:/var/opt/mssql/data
    ports:
      - 1434:1433
    networks:
     - backend
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    restart: on-failure
    command: ["start-dev"]
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password1234
      - KC_DB=mssql
      - KC_DB_URL=jdbc:sqlserver://sqlserver:1433;databaseName=keycloak;encrypt=false
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=Password1234
      - KC_TRANSACTION_XA_ENABLED=false
    volumes:
      - ./idp/data:/opt/keycloak/data
    networks:
     - backend
networks:
  backend:
    name: backend
    driver: bridge

